# https://cirrus-ci.org/guide/writing-tasks/

env:
  DOCKER_IMAGE: debian:stable-20211220-slim

# C
c_task:
  container:
    image: ${DOCKER_IMAGE}

  setup_script:
    - /bin/sh ./c/configure-debian.sh

  # tax-rate-schedules
  tax_rate_schedules_script:
    - ./c/tax-rate-schedules/test.sh

go_task:
  container:
    image: ${DOCKER_IMAGE}

  setup_script:
    - /bin/sh ./go/configure-debian.sh

  # tax-rate-schedules
  tax_rate_schedules_script:
    - ./go/tax-rate-schedules/test.sh
