# https://cirrus-ci.org/guide/writing-tasks/

# C
c_task:
  container:
    image: debian:unstable-20211220-slim

  setup_script:
    - /usr/bin/sh ./c/tax-rate-schedules

  # tax-rate-schedules
  tax_rate_schedules_script:
    - cd c/tax-rate-schedules
    - make
    - make run
